### ISSUE TITLE
 POST *attempt[2] https://autopilot.zebrunner.com/api/reporting/v1/test-runs/22/test-session  Request failed with status code 400 

### ISSUE THREAD

**Issue by ryanrosello-og** [ryanrosello-og/zebrunner-playwright-agent#22]
hey @emarf 

Would you mind taking a look into error after merging your latest changes, seems payload sent to `/test-sessions` doesn't look right

```
2022-01-16T02:48:46.679Z POST https://autopilot.zebrunner.com/api/iam/v1/auth/refresh
2022-01-16T02:48:47.748Z initialize complete: obtained refreshToken Bearer eyJ*****}
2022-01-16T02:48:47.748Z BASE_URL => https://autopilot.zebrunner.com
2022-01-16T02:48:47.748Z ACCESS_TOKEN => T1xb*****
2022-01-16T02:48:47.748Z PROJECT_KEY => DEF
2022-01-16T02:48:47.773Z POST https://autopilot.zebrunner.com/api/reporting/v1/test-runs?projectKey=DEF
testRuns >> 22
2022-01-16T02:48:48.541Z PUT https://autopilot.zebrunner.com/api/reporting/v1/test-runs/22/labels
2022-01-16T02:48:49.382Z POST https://autopilot.zebrunner.com/api/reporting/v1/test-runs/22/tests
2022-01-16T02:48:50.058Z PUT https://autopilot.zebrunner.com/api/reporting/v1/test-runs/22/tests/561/labels
2022-01-16T02:48:50.670Z POST https://autopilot.zebrunner.com/api/reporting/v1/test-runs/22/logs
2022-01-16T02:48:51.424Z PUT https://autopilot.zebrunner.com/api/reporting/v1/test-runs/22/tests/561
2022-01-16T02:48:52.035Z POST https://autopilot.zebrunner.com/api/reporting/v1/test-runs/22/test-sessions
2022-01-16T02:48:52.779Z POST https://autopilot.zebrunner.com/api/reporting/v1/test-runs/22/test-sessions
2022-01-16T02:48:54.396Z POST *attempt[1] https://autopilot.zebrunner.com/api/reporting/v1/test-runs/22/test-sessions
2022-01-16T02:48:56.112Z POST *attempt[2] https://autopilot.zebrunner.com/api/reporting/v1/test-runs/22/test-sessions
Payload: {"sessionId":"4848c9df-8854-4f4a-b5a7-77ea1e0e2f24","initiatedAt":"2022-01-16T02:48:44.459Z","startedAt":"2022-01-16T02:48:44.459Z","desiredCapabilities":{},"capabilities":{},"testIds":[561]} 
 Request failed with status code 400 
 Error: Request failed with status code 400
    at createError (/Users/it/repo/Autopilot-Automation-Playwright/node_modules/zebrunner-playwright-agent/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/Users/it/repo/Autopilot-Automation-Playwright/node_modules/zebrunner-playwright-agent/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/Users/it/repo/Autopilot-Automation-Playwright/node_modules/zebrunner-playwright-agent/node_modules/axios/lib/adapters/http.js:293:11)
    at IncomingMessage.emit (node:events:406:35)
    at endReadableNT (node:internal/streams/readable:1329:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
2022-01-16T02:48:57.888Z PUT https://autopilot.zebrunner.com/api/reporting/v1/test-runs/22
{
  testsExecutions: { success: 1, errors: 0 },
  testRunTags: { success: 1, errors: 0 },
  testTags: { success: 1, errors: 0 },
  screenshots: { success: 0, errors: 0 },
  testArtifacts: { success: 0, errors: 0 },
  videoArtifacts: { success: 0, errors: 0 },
  testStepsRequests: { success: 1, errors: 0 },
  endTestExecutions: { success: 1, errors: 0 },
  testSessions: { success: 0, errors: 1 },
  stopTestRunsResult: { success: 1, errors: 0 },
  resultsLink: 'https://autopilot.zebrunner.com/projects/DEF/test-runs/22'
}
View in Zebrunner => https://autopilot.zebrunner.com/projects/DEF/test-runs/22
Duration: 10.751s
Slack reporter disabled - skipped posting results to Slack

To open last HTML report run:

  npx playwright show-report

```

**Comment by emarf** [comment]
Can you share playwright.config.ts? i think problem because `desiredCapabilities":{},"capabilities":{}` is empty.

**Comment by ryanrosello-og** [comment]
hey @emarf 
Please clone this repo https://github.com/ryanrosello-og/zeb-issue and follow the instructions in the README to reproduce the issue.

**Comment by ryanrosello-og** [comment]
resolved by https://github.com/ryanrosello-og/zebrunner-playwright-agent/pull/23
